force-app/main/default/objects/SQX_Complaint__c/SQX_Complaint__c.object-meta.xml
<CustomObject>
    <label>Compliant</label>
    <nameField>
        <displayFormat>COM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint__c/fields/ConName__c.field-meta.xml
<CustomField>
    <fullName>ConName__c</fullName>
    <label>Primary Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/CQ_Title__c.field-meta.xml
<CustomField>
    <fullName>CQ_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint__c/fields/Customer_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact_Email__c</fullName>
    <label>Customer Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SQX_Complaint_Feedback__c/SQX_Complaint_Feedback__c.object-meta.xml
<CustomObject>
    <label>Complaint Feedback</label>
    <nameField>
        <displayFormat>COF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaint Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Complaint_Feedback__c/fields/CQ_SQX_Related_To__c.field-meta.xml
<CustomField>
    <fullName>CQ_SQX_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>SQX_Complaint__c</referenceTo>
    <relationshipLabel>Complaint Feedbacks</relationshipLabel>
    <relationshipName>Complaint_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RequestFeedbackButtonController.cls
/**
 * @description       :
 * @author            : Prashant Rathi
 * @group             :
 * @last modified on  : 07-03-2025
 * @last modified by  : Prashant Rathi
 **/
public with sharing class RequestFeedbackButtonController {
    @AuraEnabled
    public static void createFeedbackRecord(Id complaintId){
        SQX_Complaint__c complaint = [SELECT Id, CQ_Title__c, Name, Customer_Contact_Email__c, ConName__c‎ 
                                                FROM SQX_Complaint__c 
                                                WHERE Id = :complaintId WITH SECURITY_ENFORCED LIMIT 1];
        String email = complaint.Customer_Contact_Email__c;
        if (String.isBlank(email) || !Pattern.matches('^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$', email)) {
        throw new AuraHandledException('Customer Contact email is missing or invalid.');
        }
        SQX_Complaint_Feedback__c feedback = new SQX_Complaint_Feedback__c(
            CQ_SQX_Related_To__c = complaint.Id,
            CQ_Status__c = 'Requested'
        );
        insert feedback;
        sendFeedbackEmail(feedback.Id, complaint.Customer_Contact_Email__c,complaint.Name, complaint.ConName__c);
    }

    // Sending Feedback record link on email
    private static void sendFeedbackEmail(Id feedbackId, String toEmail, String complaintName, String ConName) {
        String baseUrl = URL.getOrgDomainUrl().toExternalForm();
        String formLink = baseUrl + '/lightning/r/SQX_Complaint_Feedback__c/' + feedbackId + '/view';

        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[] { toEmail });
        email.setSubject('Please fill your feedback for Compliant : '+complaintName);
        email.setPlainTextBody('Hi '+ ConName+'\n\nPlease share your thoughts by clicking the link below:\n' + formLink +'\n\n Regards\n System Admin');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
}